name: CI
on: push
jobs:
  prod-check:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 
      - name: chomd
        run: chmod a+x ./build.sh
      - name: Run build script
        run: sh ./build.sh
        shell: bash 