name: CI
on: push
jobs:
  prod-check:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./.github/scripts
    steps: 
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 
      - name: Run build script
        run: ./build.sh
        shell: bash 