name: CI
on: push
jobs:
  prod-check:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 
      - name: Run build script
        run: sh ./.github/scripts/build.sh
        shell: bash 