on:
  push:
jobs:
    print_context:
        runs-on: ubuntu-latest
        steps:
            - env:
                EVENT_CONTEXT: ${{ toJson(github.event) }}
              run: | 
                echo $EVENT_CONTEXT