name: A workflow for my Hello world file
on: push
jobs: 
  build: 
    name: Hello world action
    runs-on: ubuntu-lates
    steps: 
    - uses: actions/checkout@v1
    - uses: ./action-a
      with:
        MY_NAME: "Ferat"  