name: CI
on: push
jobs: 
  prod-check:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      First_Name: Ferat
    steps:
      - run: echo "My name is $First_Name"