name: Directory
on: 
  push:
    branches: main
jobs: 
  directory:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/scripts
    steps:
      - name: check repo
        uses: actions/checkout@v4
      - name: executable
        run: chmod +x myscript.sh
      - name: run script
        run: ./myscript.sh
  prod-check:
    needs: directory
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"    