on:
  workflow_run:
    workflows: ["Build"]
    types: [requested]
    branches: 
      - 'main'
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing workflow"
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build workflow"