name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
  first-last-name:
    runs-on: ubuntu-latest
    env: 
      First-Name: Ferat
      Last-Name: Imrak
    steps:
      - name: Print first and last name
        run: echo 'My first name is ${{env.First-Name}} and my last name is ${{env.Last-Name}}'