name: Directory
on: 
  push:
    branches: main
jobs: 
  directory:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/scripts
    steps:
      - name: check repo
        uses: actions/checkout@v4
      - name: run script
        run: ./myscript.sh