on:
  workflow_call:
    inputs:
      name:
        description: 'Name of greeting'
        required: true
        type: string
    outputs:
        greetingMessage:
            description: 'Generated greeting message'
            value: ${{ github.job.steps.greeting.output.message }}
  
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
        - id: greeting
          run: echo "::set-output name=message::Hello, ${{ inputs.name }}"